title: StoryLab Academy
description: Data journalism training by Code for Africa, Google, and World Bank.

url: https://storylab.codeforafrica.org
enforce_ssl: storylab.codeforafrica.org

registration_form: https://link.es/

google_analytics: UA-44795600-37
