title: StoryLab Academy
description: Data journalism training by Code for Africa, Google, and World Bank.

url: https://academy.codeforafrica.org
enforce_ssl: academy.codeforafrica.org

registration_form: "https://docs.google.com/forms/d/e/1FAIpQLScwSFVA8KcC0QcLq3NvWZFUB115o_hVgtjDBYLiHdJQIq6MuA/viewform?c=0&w=1"

google_analytics: UA-44795600-37
